# Docker Compose file for dev setup

services:
  exporter:
    build:
      context: ../..
    environment:
      - TZ=Europe/Oslo
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
      - HTTP_PORT=9995
      - HTTP_PATH=/nut
      #- PRINT_METRICS_AND_EXIT=true
    # ports:
    #   - "127.0.0.1:9995:9995/tcp"
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    environment:
      - TZ=Europe/Oslo
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../../.local/prometheus_data/:/prometheus/:rw
    # ports:
    #   - "127.0.0.1:9090:9090/tcp"
    network_mode: host
