name: Check

on:
  release:
    types: [published]
  push:
    branches: [ci-test]

env:
  CARGO_TERM_COLOR: always
  RELEASE_VERSION2: ${GITHUB_REF#refs/*/}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get release version
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Print release version
      run: echo $RELEASE_VERSION
    - name: Print release version 2
      run: echo $RELEASE_VERSION2
    # - name: Push to GitHub Packages
    #   uses: docker/build-push-action@v1
    #   with:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    #     registry: docker.pkg.github.com
    #     repository: "HON95/prometheus-nut-exporter/prometheus-nut-exporter:"
    #     tag_with_ref: true
