name: Check

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  IMAGE: HON95/prometheus-nut-exporter

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: "$IMAGE"
        tag_with_ref: true
